# converter
name: converter rules dat files

on:
  workflow_dispatch:
  schedule:
    - cron: "30 22 * * *" # 6:30 AM UTC+8
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          path: v2ray-rules-dat-converter
          ref: geodata

      - name: Checkout MetaCubeX/meta-rules-converter
        uses: actions/checkout@v6
        with:
          repository: MetaCubeX/meta-rules-converter
          path: convert

      - name: convert geosite
        run: |
          cd convert
          wget https://github.com/Perish1024/v2ray-rules-dat/releases/latest/download/geosite.dat
          mkdir -pv ../v2ray-rules-dat-converter/meta-rule/geo/geosite
          go run ./ geosite -f ./geosite.dat -o ../v2ray-rules-dat-converter/meta-rule/geo/geosite

      - name: convert geoip
        run: |
          cd convert
          wget https://github.com/Perish1024/geoip/releases/latest/download/geoip-lite.dat
          mkdir -pv ../v2ray-rules-dat-converter/meta-rule/geo/geoip
          go run ./ geoip -f ./geoip-lite.dat -o ../v2ray-rules-dat-converter/meta-rule/geo/geoip

      - name: git push
        run: |
          cd v2ray-rules-dat-converter
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add .
          if [[ $(git diff HEAD --stat) != '' ]]; then
            git commit -m "$(TZ=Asia/Shanghai date +%Y-%m-%dT%H:%M:%S%z) update"
            git push origin geodata
          fi
